// MUSICS
export const GET_MUSICS_SUCCESS = 'GET_MUSICS_SUCCESS';
export const GET_MUSICS_SELECTION_SUCCESS = 'GET_MUSICS_SELECTION_SUCCESS';
export const RESET_MUSICS_SUCCESS = 'RESET_MUSICS_SUCCESS';

// USERS
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';

// SCORES
export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCCESS';
export const RESET_SCORE_SUCCESS = 'RESET_SCORE_SUCCESS';

// HISTORY
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const ADD_HISTORY_SUCCESS = 'ADD_HISTORY_SUCCESS';

// GAMES
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const RESET_GAME_SUCCESS = 'RESET_GAME_SUCCESS';

// MOVIES
export const SAVE_COVER_SUCCESS = 'SAVE_COVER_SUCCESS';
export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const FIND_MOVIES_SUCCESS = 'FIND_MOVIES_SUCCESS';
export const SAVE_SELECTED_MOVIE_SUCCESS = 'SAVE_SELECTED_MOVIE_SUCCESS';
export const RESET_MOVIE_SEARCH_SUCCESS = 'RESET_MOVIE_SEARCH_SUCCESS';

// SHOWS
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const FIND_SHOWS_SUCCESS = 'FIND_SHOWS_SUCCESS';
export const SAVE_SELECTED_SHOW_SUCCESS = 'SAVE_SELECTED_SHOW_SUCCESS';
export const RESET_SHOW_SEARCH_SUCCESS = 'RESET_SHOW_SEARCH_SUCCESS';

// MUSIC OF THE DAY
export const GET_TODAY_MUSIC_SUCCESS = 'GET_TODAY_MUSIC_SUCCESS';

// HISTORY OF THE DAY
export const GET_ALL_HISTORY_TODAY_SUCCESS = 'GET_ALL_HISTORY_TODAY_SUCCESS';
export const GET_HISTORY_TODAY_SUCCESS = 'GET_HISTORY_TODAY_SUCCESS';
export const SAVE_HISTORY_TODAY_SUCCESS = 'SAVE_HISTORY_TODAY_SUCCESS';

// CATEGORIES
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

// NOTIFICATIONS
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const MARK_AS_READ_NOTIFICATION_SUCCESS =
  'MARK_AS_READ_NOTIFICATION_SUCCESS';
