// MUSICS
export const GET_MUSICS_SUCCESS = 'GET_MUSICS_SUCCESS';
export const GET_MUSICS_SELECTION_SUCCESS = 'GET_MUSICS_SELECTION_SUCCESS';
export const RESET_MUSICS_SUCCESS = 'RESET_MUSICS_SUCCESS';

// USERS
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';

// SCORES
export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCCESS';
export const RESET_SCORE_SUCCESS = 'RESET_SCORE_SUCCESS';

// GAME SETTINGS
export const EDIT_GAME_SETTINGS_SUCCESS = 'EDIT_GAME_SETTINGS_SUCCESS';

// HISTORY
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const ADD_HISTORY_SUCCESS = 'ADD_HISTORY_SUCCESS';

// GAMES
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';

// MOVIES
export const SAVE_COVER_SUCCESS = 'SAVE_COVER_SUCCESS';

// MUSIC OF THE DAY
export const GET_TODAY_MUSIC_SUCCESS = 'GET_TODAY_MUSIC_SUCCESS';

// HISTORY OF THE DAY
export const GET_ALL_HISTORY_TODAY_SUCCESS = 'GET_ALL_HISTORY_TODAY_SUCCESS';
export const GET_HISTORY_TODAY_SUCCESS = 'GET_HISTORY_TODAY_SUCCESS';
export const SAVE_HISTORY_TODAY_SUCCESS = 'SAVE_HISTORY_TODAY_SUCCESS';
