name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: fifsky/ssh-action@master
        with:
          host: 195.15.223.247
          user: debian
          key: ${{ secrets.RSA_KEY }}
          command: |
            cd /tmp
            ls -a
          # script: |
          #   cd /home/debian/www/blindtus/client
          #   git pull origin main
          #   git status
