name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          command: |
            cd /home/debian/www/blindtus/client
            git pull origin main
            git status
            yarn build
            pm2 reload all
